extern crate mithril;
#[macro_use(assert_diff)]
extern crate difference;

use mithril::randomx::superscalar::{Blake2Generator, ScProgram};

#[test]
fn test_generate_1() {
	let key_str = b"test key 000";
	let mut gen = Blake2Generator::new(key_str, 0);
	let prog = ScProgram::generate(&mut gen);
	assert_diff!(EXPECTED_SUPERSCALAR_PROG_1, &prog.to_string(), "\n", 0);
}

#[test]
fn test_generate_666() {
	let key_str = b"666";
	let mut gen = Blake2Generator::new(key_str, 0);
	let prog = ScProgram::generate(&mut gen);

	assert_diff!(EXPECTED_SUPERSCALAR_PROG_666, &prog.to_string(), "\n", 0);
}

#[test]
fn test_generate_rage() {
	let key_str = b"RageAgainstTheMachine";
	let mut gen = Blake2Generator::new(key_str, 0);
	let prog = ScProgram::generate(&mut gen);
	assert_diff!(EXPECTED_SUPERSCALAR_PROG_RAGE, &prog.to_string(), "\n", 0);
}

//helper + testdata

const EXPECTED_SUPERSCALAR_PROG_1: &str = r#"op: IMUL_R, src: 0, dst: 3
op: IMUL_R, src: 1, dst: 4
op: IMUL_R, src: 7, dst: 6
op: IROR_C, src: -1, dst: 7
op: IADD_RS, src: 1, dst: 2
op: IXOR_C9, src: -1, dst: 0
op: ISMULH_R, src: 5, dst: 1
op: IMUL_RCP, src: -1, dst: 0
op: IADD_C8, src: -1, dst: 5
op: IROR_C, src: -1, dst: 4
op: IROR_C, src: -1, dst: 3
op: IADD_C9, src: -1, dst: 3
op: ISMULH_R, src: 3, dst: 7
op: IMUL_RCP, src: -1, dst: 1
op: IMUL_R, src: 2, dst: 3
op: IMUL_R, src: 4, dst: 0
op: IROR_C, src: -1, dst: 2
op: IADD_C7, src: -1, dst: 6
op: IXOR_R, src: 2, dst: 4
op: ISUB_R, src: 4, dst: 5
op: IXOR_R, src: 2, dst: 6
op: IADD_C7, src: -1, dst: 5
op: IXOR_R, src: 2, dst: 7
op: IXOR_R, src: 6, dst: 2
op: ISMULH_R, src: 4, dst: 4
op: IMUL_RCP, src: -1, dst: 6
op: IMUL_R, src: 5, dst: 2
op: IMUL_R, src: 0, dst: 5
op: IADD_RS, src: 7, dst: 1
op: IXOR_C7, src: -1, dst: 0
op: ISUB_R, src: 3, dst: 1
op: ISUB_R, src: 3, dst: 2
op: IXOR_R, src: 3, dst: 7
op: ISUB_R, src: 3, dst: 0
op: IXOR_C7, src: -1, dst: 2
op: ISUB_R, src: 1, dst: 3
op: IXOR_R, src: 2, dst: 4
op: IMUL_R, src: 2, dst: 1
op: IMUL_R, src: 0, dst: 3
op: IMUL_R, src: 6, dst: 4
op: IROR_C, src: -1, dst: 0
op: IXOR_R, src: 7, dst: 0
op: IXOR_C7, src: -1, dst: 5
op: IXOR_R, src: 6, dst: 2
op: IXOR_R, src: 7, dst: 6
op: IADD_RS, src: 2, dst: 6
op: IXOR_C9, src: -1, dst: 0
op: ISUB_R, src: 5, dst: 2
op: IMUL_R, src: 2, dst: 0
op: IMUL_R, src: 2, dst: 6
op: IMUL_R, src: 4, dst: 2
op: IROR_C, src: -1, dst: 3
op: IROR_C, src: -1, dst: 1
op: IADD_C9, src: -1, dst: 5
op: IMULH_R, src: 3, dst: 7
op: IMUL_RCP, src: -1, dst: 1
op: IXOR_C9, src: -1, dst: 3
op: IMULH_R, src: 4, dst: 4
op: IMUL_RCP, src: -1, dst: 2
op: IXOR_C8, src: -1, dst: 5
op: IADD_RS, src: 3, dst: 0
op: IROR_C, src: -1, dst: 5
op: IXOR_C9, src: -1, dst: 5
op: ISMULH_R, src: 0, dst: 3
op: IMUL_RCP, src: -1, dst: 0
op: IMUL_R, src: 5, dst: 4
op: IMUL_R, src: 7, dst: 1
op: IADD_RS, src: 5, dst: 6
op: IROR_C, src: -1, dst: 5
op: IXOR_C8, src: -1, dst: 6
op: IROR_C, src: -1, dst: 7
op: IROR_C, src: -1, dst: 6
op: IADD_C9, src: -1, dst: 5
op: ISUB_R, src: 7, dst: 2
op: IMUL_R, src: 7, dst: 0
op: IMUL_R, src: 2, dst: 5
op: IMUL_R, src: 1, dst: 2
op: IROR_C, src: -1, dst: 3
op: IADD_RS, src: 7, dst: 6
op: IADD_C8, src: -1, dst: 6
op: IROR_C, src: -1, dst: 4
op: IADD_RS, src: 7, dst: 6
op: IXOR_C8, src: -1, dst: 4
op: IROR_C, src: -1, dst: 6
op: IMUL_R, src: 7, dst: 4
op: IMUL_R, src: 0, dst: 3
op: IMUL_R, src: 1, dst: 7
op: IADD_RS, src: 0, dst: 6
op: IADD_RS, src: 6, dst: 0
op: IADD_C9, src: -1, dst: 1
op: IMULH_R, src: 1, dst: 1
op: IMUL_RCP, src: -1, dst: 6
op: IADD_C8, src: -1, dst: 0
op: IADD_RS, src: 5, dst: 2
op: IROR_C, src: -1, dst: 4
op: IXOR_C9, src: -1, dst: 0
op: ISUB_R, src: 4, dst: 2
op: IMUL_R, src: 4, dst: 0
op: IMUL_R, src: 5, dst: 4
op: IMUL_R, src: 7, dst: 2
op: IROR_C, src: -1, dst: 5
op: IXOR_C7, src: -1, dst: 7
op: IXOR_R, src: 5, dst: 7
op: ISUB_R, src: 5, dst: 3
op: IMULH_R, src: 3, dst: 5
op: IMUL_RCP, src: -1, dst: 4
op: IADD_C9, src: -1, dst: 6
op: ISMULH_R, src: 6, dst: 7
op: IMUL_RCP, src: -1, dst: 0
op: IXOR_C9, src: -1, dst: 1
op: ISMULH_R, src: 2, dst: 3
op: IMUL_RCP, src: -1, dst: 5
op: IADD_C9, src: -1, dst: 2
op: ISUB_R, src: 1, dst: 2
op: IXOR_R, src: 1, dst: 6
op: IXOR_C7, src: -1, dst: 6
op: ISUB_R, src: 1, dst: 6
op: IMULH_R, src: 2, dst: 1
op: IMUL_RCP, src: -1, dst: 2
op: IMUL_R, src: 7, dst: 6
op: IMUL_R, src: 5, dst: 4
op: IROR_C, src: -1, dst: 7
op: IROR_C, src: -1, dst: 0
op: IADD_C9, src: -1, dst: 7
op: ISMULH_R, src: 0, dst: 7
op: IMUL_RCP, src: -1, dst: 0
op: IXOR_C8, src: -1, dst: 3
op: IADD_RS, src: 5, dst: 3
op: IROR_C, src: -1, dst: 5
op: IXOR_C9, src: -1, dst: 5
op: IMULH_R, src: 6, dst: 1
op: IMUL_RCP, src: -1, dst: 5
op: IMUL_R, src: 0, dst: 7
op: IMUL_R, src: 6, dst: 0
op: IADD_RS, src: 6, dst: 3
op: IADD_C7, src: -1, dst: 6
op: IXOR_R, src: 6, dst: 3
op: IXOR_R, src: 6, dst: 4
op: ISUB_R, src: 4, dst: 3
op: IXOR_C7, src: -1, dst: 4
op: IXOR_R, src: 4, dst: 2
op: IXOR_R, src: 3, dst: 6
op: ISMULH_R, src: 4, dst: 4
op: IMUL_RCP, src: -1, dst: 6
op: IMUL_R, src: 3, dst: 5
op: IMUL_R, src: 0, dst: 1
op: IADD_RS, src: 7, dst: 2
op: IROR_C, src: -1, dst: 7
op: IADD_C9, src: -1, dst: 2
op: IMULH_R, src: 3, dst: 3
op: IMUL_RCP, src: -1, dst: 2
op: IXOR_C9, src: -1, dst: 7
op: IMULH_R, src: 4, dst: 0
op: IMUL_RCP, src: -1, dst: 7
op: IXOR_C9, src: -1, dst: 4
op: IMULH_R, src: 3, dst: 6
op: IMUL_RCP, src: -1, dst: 3
op: IADD_C8, src: -1, dst: 5
op: IROR_C, src: -1, dst: 4
op: IADD_RS, src: 4, dst: 1
op: IXOR_C8, src: -1, dst: 5
op: IADD_RS, src: 5, dst: 2
op: IMUL_R, src: 4, dst: 2
op: IMUL_R, src: 5, dst: 1
op: IMUL_R, src: 5, dst: 6
op: IADD_RS, src: 5, dst: 4
op: IADD_RS, src: 7, dst: 4
op: IADD_C9, src: -1, dst: 5
op: IMULH_R, src: 0, dst: 5
op: IMUL_RCP, src: -1, dst: 2
op: IXOR_C8, src: -1, dst: 4
op: IADD_RS, src: 0, dst: 7
op: IADD_RS, src: 3, dst: 7
op: IADD_C8, src: -1, dst: 4
op: IADD_RS, src: 0, dst: 3
op: IMUL_R, src: 4, dst: 7
op: IMUL_R, src: 1, dst: 0
op: IMUL_R, src: 1, dst: 3
op: IROR_C, src: -1, dst: 4
op: IXOR_R, src: 1, dst: 6
op: IXOR_C7, src: -1, dst: 1
op: ISUB_R, src: 1, dst: 4
op: IMULH_R, src: 2, dst: 1
op: IMUL_RCP, src: -1, dst: 6
op: IXOR_C8, src: -1, dst: 4
op: IADD_RS, src: 2, dst: 4
op: IROR_C, src: -1, dst: 2
op: IADD_C8, src: -1, dst: 2
op: IROR_C, src: -1, dst: 7
op: IMUL_R, src: 4, dst: 2
op: IMUL_R, src: 0, dst: 7
op: IMUL_R, src: 0, dst: 5
op: IROR_C, src: -1, dst: 4
op: IADD_RS, src: 4, dst: 0
op: IADD_C9, src: -1, dst: 4
op: IXOR_R, src: 0, dst: 4
op: IADD_RS, src: 0, dst: 3
op: IADD_C9, src: -1, dst: 0
op: ISUB_R, src: 6, dst: 4
op: IMUL_R, src: 2, dst: 3
op: IMUL_R, src: 4, dst: 1
op: IMUL_R, src: 4, dst: 6
op: IADD_RS, src: 2, dst: 0
op: ISUB_R, src: 4, dst: 2
op: IADD_C7, src: -1, dst: 4
op: IXOR_R, src: 2, dst: 7
op: ISUB_R, src: 0, dst: 7
op: ISUB_R, src: 0, dst: 5
op: IXOR_C7, src: -1, dst: 2
op: IXOR_R, src: 3, dst: 5
op: IXOR_R, src: 3, dst: 7
op: IMUL_R, src: 2, dst: 7
op: IMUL_R, src: 3, dst: 2
op: IMUL_R, src: 0, dst: 4
op: IROR_C, src: -1, dst: 1
op: IADD_C7, src: -1, dst: 3
op: IXOR_R, src: 1, dst: 6
op: IXOR_R, src: 3, dst: 1
op: IMULH_R, src: 5, dst: 0
op: IMUL_RCP, src: -1, dst: 3
op: IXOR_C9, src: -1, dst: 1
op: ISUB_R, src: 7, dst: 5
op: IADD_RS, src: 5, dst: 1
op: IADD_C9, src: -1, dst: 5
op: ISUB_R, src: 5, dst: 4
op: IMUL_R, src: 1, dst: 5
op: IMUL_R, src: 4, dst: 6
op: IMUL_R, src: 2, dst: 1
op: IROR_C, src: -1, dst: 2
op: IXOR_R, src: 2, dst: 4
op: IADD_C7, src: -1, dst: 2
op: ISUB_R, src: 0, dst: 3
op: IXOR_R, src: 4, dst: 7
op: ISUB_R, src: 0, dst: 2
op: IXOR_C7, src: -1, dst: 5
op: ISUB_R, src: 4, dst: 7
op: ISUB_R, src: 0, dst: 7
op: IMUL_R, src: 3, dst: 2
op: IMUL_R, src: 1, dst: 3
op: IMUL_R, src: 0, dst: 7
op: IADD_RS, src: 6, dst: 0
op: IXOR_R, src: 1, dst: 4
op: IXOR_C7, src: -1, dst: 0
op: ISUB_R, src: 5, dst: 6
op: ISUB_R, src: 4, dst: 0
op: IXOR_R, src: 1, dst: 2
op: IXOR_C7, src: -1, dst: 6
op: ISUB_R, src: 5, dst: 1
op: ISMULH_R, src: 1, dst: 5
op: IMUL_RCP, src: -1, dst: 4
op: IMUL_R, src: 3, dst: 2
op: IMUL_R, src: 1, dst: 6
op: IROR_C, src: -1, dst: 7
op: IADD_RS, src: 0, dst: 3
op: IADD_C9, src: -1, dst: 7
op: IMULH_R, src: 5, dst: 1
op: IMUL_RCP, src: -1, dst: 0
op: IADD_C9, src: -1, dst: 3
op: IXOR_R, src: 7, dst: 3
op: IXOR_C7, src: -1, dst: 7
op: ISUB_R, src: 4, dst: 2
op: IXOR_R, src: 4, dst: 5
op: ISUB_R, src: 3, dst: 2
op: IMUL_R, src: 6, dst: 3
op: IMUL_R, src: 2, dst: 4
op: IMUL_R, src: 1, dst: 5
op: IADD_RS, src: 7, dst: 6
op: IADD_C7, src: -1, dst: 6
op: IXOR_R, src: 7, dst: 2
op: ISUB_R, src: 0, dst: 7
op: ISUB_R, src: 0, dst: 1
op: IADD_C7, src: -1, dst: 0
op: IXOR_R, src: 6, dst: 1
op: ISUB_R, src: 6, dst: 2
op: IXOR_R, src: 0, dst: 1
op: IMUL_R, src: 2, dst: 0
op: IMUL_R, src: 5, dst: 7
op: IMUL_R, src: 6, dst: 2
op: IROR_C, src: -1, dst: 6
op: IADD_C7, src: -1, dst: 1
op: IXOR_R, src: 4, dst: 6
op: IXOR_R, src: 3, dst: 5
op: ISMULH_R, src: 1, dst: 3
op: IMUL_RCP, src: -1, dst: 5
op: IADD_C9, src: -1, dst: 6
op: IMULH_R, src: 0, dst: 4
op: IMUL_RCP, src: -1, dst: 1
op: IADD_C8, src: -1, dst: 7
op: IROR_C, src: -1, dst: 6
op: IXOR_R, src: 6, dst: 0
op: IADD_C7, src: -1, dst: 2
op: ISUB_R, src: 5, dst: 0
op: ISMULH_R, src: 7, dst: 7
op: IMUL_RCP, src: -1, dst: 3
op: IMUL_R, src: 5, dst: 6
op: IMUL_R, src: 4, dst: 0
op: IROR_C, src: -1, dst: 5
op: IADD_C7, src: -1, dst: 5
op: ISUB_R, src: 4, dst: 2
op: ISUB_R, src: 1, dst: 6
op: IMULH_R, src: 1, dst: 1
op: IMUL_RCP, src: -1, dst: 7
op: IXOR_C9, src: -1, dst: 5
op: IXOR_R, src: 2, dst: 6
op: IADD_RS, src: 2, dst: 4
op: IXOR_C9, src: -1, dst: 2
op: ISUB_R, src: 5, dst: 6
op: IMUL_R, src: 5, dst: 3
op: IMUL_R, src: 2, dst: 6
op: IMUL_R, src: 5, dst: 1
op: IADD_RS, src: 5, dst: 0
op: IADD_RS, src: 0, dst: 7
op: IXOR_C8, src: -1, dst: 4
op: IADD_RS, src: 4, dst: 0
op: IADD_C7, src: -1, dst: 5
op: ISUB_R, src: 7, dst: 2
op: IXOR_R, src: 3, dst: 5
op: IMULH_R, src: 5, dst: 4
op: IMUL_RCP, src: -1, dst: 0
op: IMUL_R, src: 3, dst: 7
op: IMUL_R, src: 6, dst: 2
op: IROR_C, src: -1, dst: 6
op: IADD_C7, src: -1, dst: 5
op: IXOR_R, src: 5, dst: 3
op: IXOR_R, src: 1, dst: 5
op: ISUB_R, src: 1, dst: 3
op: ISUB_R, src: 5, dst: 6
op: IADD_C7, src: -1, dst: 5
op: ISUB_R, src: 0, dst: 1
op: ISUB_R, src: 3, dst: 0
op: IMUL_R, src: 0, dst: 3
op: IMUL_R, src: 2, dst: 5
op: IMUL_R, src: 4, dst: 0
op: IROR_C, src: -1, dst: 7
op: IADD_RS, src: 6, dst: 4
op: IXOR_C8, src: -1, dst: 4
op: IADD_RS, src: 1, dst: 6
op: IADD_RS, src: 6, dst: 2
op: IXOR_C9, src: -1, dst: 7
op: ISUB_R, src: 3, dst: 1
op: IMUL_R, src: 6, dst: 2
op: IMUL_R, src: 6, dst: 7
op: IMUL_R, src: 0, dst: 6
op: IROR_C, src: -1, dst: 3
op: IXOR_R, src: 3, dst: 5
op: IADD_C7, src: -1, dst: 4
op: IXOR_R, src: 4, dst: 1
op: IXOR_R, src: 0, dst: 5
op: ISUB_R, src: 5, dst: 2
op: IXOR_C7, src: -1, dst: 1
op: ISUB_R, src: 0, dst: 5
op: IXOR_R, src: 7, dst: 5
op: IMUL_R, src: 7, dst: 1
op: IMUL_R, src: 4, dst: 2
op: IMUL_R, src: 3, dst: 5
op: IADD_RS, src: 3, dst: 4
op: IADD_RS, src: 7, dst: 6
op: IXOR_C8, src: -1, dst: 4
op: IROR_C, src: -1, dst: 7
op: IXOR_R, src: 4, dst: 0
op: IXOR_C7, src: -1, dst: 1
op: IXOR_R, src: 7, dst: 4
op: IXOR_R, src: 6, dst: 0
op: IMUL_R, src: 0, dst: 7
op: IMUL_R, src: 2, dst: 4
op: IMUL_R, src: 5, dst: 3
op: IROR_C, src: -1, dst: 2
op: IADD_RS, src: 6, dst: 1
op: IADD_C8, src: -1, dst: 2
op: IROR_C, src: -1, dst: 5
op: IADD_RS, src: 0, dst: 1
op: IXOR_C8, src: -1, dst: 2
op: IADD_RS, src: 5, dst: 7
op: IMUL_R, src: 1, dst: 5
op: IMUL_R, src: 0, dst: 2
op: IMUL_R, src: 1, dst: 7
op: IROR_C, src: -1, dst: 0
op: IROR_C, src: -1, dst: 6
op: IADD_C9, src: -1, dst: 1
op: IXOR_R, src: 3, dst: 1
op: IADD_C7, src: -1, dst: 0
op: IXOR_R, src: 4, dst: 6
op: ISUB_R, src: 3, dst: 4
op: IXOR_R, src: 0, dst: 1
op: IMUL_R, src: 2, dst: 4
op: IMUL_R, src: 0, dst: 6
op: IMUL_R, src: 2, dst: 0
op: IROR_C, src: -1, dst: 5
op: IADD_RS, src: 2, dst: 3
op: IADD_C8, src: -1, dst: 1
op: IADD_RS, src: 2, dst: 7
op: IROR_C, src: -1, dst: 2
op: IADD_C9, src: -1, dst: 3
op: ISUB_R, src: 2, dst: 3
op: IMUL_R, src: 7, dst: 1
op: IMUL_R, src: 3, dst: 2
op: IMUL_R, src: 3, dst: 7
op: IADD_RS, src: 5, dst: 4
op: IROR_C, src: -1, dst: 6
op: IXOR_C9, src: -1, dst: 5
op: ISUB_R, src: 4, dst: 6
op: ISUB_R, src: 5, dst: 3
op: IADD_C7, src: -1, dst: 1
op: ISUB_R, src: 4, dst: 5
op: IXOR_R, src: 4, dst: 3
op: IMUL_R, src: 3, dst: 5
op: IMUL_R, src: 0, dst: 6
op: IMUL_R, src: 3, dst: 1
op: IADD_RS, src: 2, dst: 3
op: IADD_RS, src: 7, dst: 2
op: IADD_C8, src: -1, dst: 0
op: IROR_C, src: -1, dst: 7
op: IADD_RS, src: 0, dst: 4
op: IADD_C8, src: -1, dst: 7
op: IADD_RS, src: 2, dst: 0
op: IMUL_R, src: 3, dst: 2
op: IMUL_R, src: 6, dst: 3
op: IMUL_R, src: 6, dst: 4
op: IROR_C, src: -1, dst: 7
op: IADD_RS, src: 5, dst: 7
op: IXOR_C9, src: -1, dst: 0
op: IMULH_R, src: 2, dst: 5
op: IMUL_RCP, src: -1, dst: 6
op: IXOR_C8, src: -1, dst: 7
op: IROR_C, src: -1, dst: 1
op: IADD_C7, src: -1, dst: 3
op: ISUB_R, src: 7, dst: 2
op: ISUB_R, src: 1, dst: 7
op: ISUB_R, src: 2, dst: 1
op: IMUL_R, src: 3, dst: 0
op: IMUL_R, src: 4, dst: 2
op: IMUL_R, src: 1, dst: 5
op: IADD_RS, src: 3, dst: 7
op: ISUB_R, src: 4, dst: 3
op: IADD_C7, src: -1, dst: 3
op: ISUB_R, src: 4, dst: 7
op: ISUB_R, src: 1, dst: 0
op: IADD_RS, src: 3, dst: 6
op: IADD_C9, src: -1, dst: 7
op: IMULH_R, src: 7, dst: 1
op: IMUL_RCP, src: -1, dst: 3
op: IMUL_R, src: 5, dst: 6
op: IMUL_R, src: 5, dst: 0
op: IADD_RS, src: 7, dst: 2
op: IROR_C, src: -1, dst: 7
op: IXOR_C9, src: -1, dst: 7
op: ISMULH_R, src: 2, dst: 4
"#;

const EXPECTED_SUPERSCALAR_PROG_666: &str = r#"op: IMUL_R, src: 4, dst: 3
op: IMUL_R, src: 0, dst: 6
op: IMUL_R, src: 1, dst: 7
op: IADD_RS, src: 4, dst: 1
op: IXOR_C7, src: -1, dst: 1
op: ISUB_R, src: 5, dst: 4
op: IXOR_R, src: 4, dst: 5
op: ISMULH_R, src: 0, dst: 0
op: IMUL_RCP, src: -1, dst: 6
op: IXOR_C8, src: -1, dst: 2
op: IROR_C, src: -1, dst: 3
op: ISUB_R, src: 4, dst: 5
op: IADD_C7, src: -1, dst: 1
op: ISUB_R, src: 3, dst: 2
op: IXOR_R, src: 3, dst: 7
op: IMUL_R, src: 1, dst: 5
op: IMUL_R, src: 3, dst: 0
op: IMUL_R, src: 4, dst: 6
op: IROR_C, src: -1, dst: 7
op: IADD_RS, src: 4, dst: 2
op: IXOR_C8, src: -1, dst: 3
op: IADD_RS, src: 7, dst: 1
op: IADD_RS, src: 4, dst: 3
op: IADD_C8, src: -1, dst: 1
op: IROR_C, src: -1, dst: 4
op: IMUL_R, src: 3, dst: 1
op: IMUL_R, src: 5, dst: 7
op: IMUL_R, src: 2, dst: 4
op: IADD_RS, src: 5, dst: 3
op: IXOR_C7, src: -1, dst: 2
op: IXOR_R, src: 0, dst: 3
op: IXOR_R, src: 2, dst: 0
op: IMULH_R, src: 1, dst: 5
op: IMUL_RCP, src: -1, dst: 1
op: IXOR_C8, src: -1, dst: 3
op: IROR_C, src: -1, dst: 7
op: IROR_C, src: -1, dst: 0
op: IADD_C9, src: -1, dst: 3
op: IMULH_R, src: 2, dst: 2
op: IMUL_RCP, src: -1, dst: 0
op: IMUL_R, src: 4, dst: 7
op: IMUL_R, src: 4, dst: 5
op: IROR_C, src: -1, dst: 6
op: ISUB_R, src: 6, dst: 4
op: IADD_C7, src: -1, dst: 1
op: ISUB_R, src: 1, dst: 7
op: ISMULH_R, src: 6, dst: 3
op: IMUL_RCP, src: -1, dst: 6
op: IADD_C9, src: -1, dst: 4
op: ISMULH_R, src: 7, dst: 1
op: IMUL_RCP, src: -1, dst: 2
op: IXOR_C9, src: -1, dst: 7
op: ISUB_R, src: 4, dst: 0
op: IADD_C7, src: -1, dst: 0
op: ISUB_R, src: 7, dst: 4
op: ISUB_R, src: 4, dst: 6
op: IMULH_R, src: 7, dst: 7
op: IMUL_RCP, src: -1, dst: 5
op: IMUL_R, src: 3, dst: 0
op: IMUL_R, src: 4, dst: 2
op: IROR_C, src: -1, dst: 3
op: ISUB_R, src: 3, dst: 4
op: IADD_C7, src: -1, dst: 1
op: IXOR_R, src: 3, dst: 6
op: ISUB_R, src: 4, dst: 0
op: IROR_C, src: -1, dst: 4
op: IADD_C8, src: -1, dst: 3
op: IROR_C, src: -1, dst: 6
op: IMUL_R, src: 1, dst: 0
op: IMUL_R, src: 5, dst: 3
op: IMUL_R, src: 1, dst: 4
op: IROR_C, src: -1, dst: 1
op: IROR_C, src: -1, dst: 5
op: IADD_C8, src: -1, dst: 1
op: IADD_RS, src: 1, dst: 0
op: IADD_C7, src: -1, dst: 7
op: ISUB_R, src: 5, dst: 6
op: ISUB_R, src: 6, dst: 1
op: IMULH_R, src: 4, dst: 2
op: IMUL_RCP, src: -1, dst: 1
op: IMUL_R, src: 7, dst: 6
op: IMUL_R, src: 6, dst: 7
op: IROR_C, src: -1, dst: 3
op: IXOR_R, src: 4, dst: 5
op: IXOR_C7, src: -1, dst: 4
op: IXOR_R, src: 0, dst: 6
op: ISMULH_R, src: 4, dst: 0
op: IMUL_RCP, src: -1, dst: 6
op: IXOR_C8, src: -1, dst: 3
op: IADD_RS, src: 4, dst: 2
op: IROR_C, src: -1, dst: 3
op: IADD_C8, src: -1, dst: 2
op: IROR_C, src: -1, dst: 5
op: IMUL_R, src: 1, dst: 3
op: IMUL_R, src: 5, dst: 4
op: IMUL_R, src: 2, dst: 6
op: IROR_C, src: -1, dst: 1
op: IROR_C, src: -1, dst: 2
op: IADD_C8, src: -1, dst: 7
op: IADD_RS, src: 2, dst: 0
op: ISUB_R, src: 0, dst: 2
op: IXOR_C7, src: -1, dst: 1
op: IXOR_R, src: 3, dst: 0
op: ISUB_R, src: 3, dst: 2
op: IMUL_R, src: 1, dst: 7
op: IMUL_R, src: 3, dst: 5
op: IMUL_R, src: 1, dst: 2
op: IROR_C, src: -1, dst: 4
op: IXOR_R, src: 6, dst: 3
op: IXOR_C7, src: -1, dst: 4
op: ISUB_R, src: 4, dst: 3
op: IXOR_R, src: 0, dst: 4
op: IROR_C, src: -1, dst: 7
op: IXOR_C8, src: -1, dst: 3
op: IROR_C, src: -1, dst: 0
op: IMUL_R, src: 6, dst: 4
op: IMUL_R, src: 5, dst: 1
op: IMUL_R, src: 5, dst: 7
op: IROR_C, src: -1, dst: 6
op: IROR_C, src: -1, dst: 2
op: IXOR_C9, src: -1, dst: 6
op: ISUB_R, src: 5, dst: 4
op: IADD_RS, src: 6, dst: 0
op: IADD_C8, src: -1, dst: 2
op: IADD_RS, src: 0, dst: 4
op: IMUL_R, src: 1, dst: 6
op: IMUL_R, src: 0, dst: 3
op: IMUL_R, src: 4, dst: 0
op: IROR_C, src: -1, dst: 5
op: ISUB_R, src: 2, dst: 4
op: IXOR_C7, src: -1, dst: 2
op: ISUB_R, src: 7, dst: 4
op: IXOR_R, src: 7, dst: 1
op: ISUB_R, src: 2, dst: 6
op: IXOR_C7, src: -1, dst: 4
op: ISUB_R, src: 7, dst: 1
op: IMULH_R, src: 5, dst: 7
op: IMUL_RCP, src: -1, dst: 3
op: IMUL_R, src: 4, dst: 6
op: IMUL_R, src: 4, dst: 5
op: IADD_RS, src: 4, dst: 1
op: IADD_C7, src: -1, dst: 0
op: ISUB_R, src: 4, dst: 2
op: ISUB_R, src: 1, dst: 4
op: ISUB_R, src: 4, dst: 0
op: ISUB_R, src: 1, dst: 2
op: IXOR_C7, src: -1, dst: 4
op: ISUB_R, src: 7, dst: 3
op: IXOR_R, src: 2, dst: 0
op: IMUL_R, src: 0, dst: 4
op: IMUL_R, src: 2, dst: 1
op: IMUL_R, src: 5, dst: 0
op: IROR_C, src: -1, dst: 3
op: IROR_C, src: -1, dst: 6
op: IXOR_C9, src: -1, dst: 6
op: IXOR_R, src: 5, dst: 2
op: IROR_C, src: -1, dst: 2
op: IXOR_C9, src: -1, dst: 5
op: ISUB_R, src: 4, dst: 3
op: IMUL_R, src: 2, dst: 5
op: IMUL_R, src: 4, dst: 2
op: IMUL_R, src: 3, dst: 7
op: IROR_C, src: -1, dst: 6
op: IXOR_R, src: 1, dst: 3
op: IADD_C7, src: -1, dst: 1
op: IXOR_R, src: 4, dst: 3
op: IMULH_R, src: 6, dst: 4
op: IMUL_RCP, src: -1, dst: 3
op: IADD_C8, src: -1, dst: 0
op: IADD_RS, src: 0, dst: 1
op: IROR_C, src: -1, dst: 5
op: IXOR_C8, src: -1, dst: 7
op: IROR_C, src: -1, dst: 1
op: IMUL_R, src: 2, dst: 5
op: IMUL_R, src: 2, dst: 1
op: IMUL_R, src: 7, dst: 4
op: IADD_RS, src: 2, dst: 6
op: ISUB_R, src: 7, dst: 2
op: IADD_C7, src: -1, dst: 3
op: ISUB_R, src: 0, dst: 6
op: IXOR_R, src: 6, dst: 7
op: IADD_C7, src: -1, dst: 6
op: IXOR_R, src: 3, dst: 2
op: ISUB_R, src: 7, dst: 1
op: ISUB_R, src: 3, dst: 5
op: IMUL_R, src: 2, dst: 0
op: IMUL_R, src: 6, dst: 3
op: IMUL_R, src: 6, dst: 7
op: IROR_C, src: -1, dst: 6
op: IADD_RS, src: 2, dst: 4
op: IADD_C9, src: -1, dst: 6
op: IXOR_R, src: 4, dst: 2
op: IADD_C7, src: -1, dst: 1
op: ISUB_R, src: 5, dst: 2
op: IXOR_R, src: 0, dst: 4
op: ISUB_R, src: 5, dst: 4
op: IMUL_R, src: 6, dst: 1
op: IMUL_R, src: 6, dst: 5
op: IMUL_R, src: 0, dst: 4
op: IROR_C, src: -1, dst: 2
op: IADD_C7, src: -1, dst: 2
op: ISUB_R, src: 0, dst: 6
op: ISUB_R, src: 0, dst: 2
op: ISMULH_R, src: 3, dst: 0
op: IMUL_RCP, src: -1, dst: 1
op: IADD_C8, src: -1, dst: 2
op: IADD_RS, src: 7, dst: 2
op: IXOR_C7, src: -1, dst: 3
op: ISUB_R, src: 2, dst: 7
op: ISUB_R, src: 4, dst: 6
op: IXOR_R, src: 5, dst: 4
op: IMUL_R, src: 5, dst: 4
op: IMUL_R, src: 3, dst: 7
op: IMUL_R, src: 2, dst: 6
op: IADD_RS, src: 3, dst: 2
op: ISUB_R, src: 5, dst: 3
op: IADD_C7, src: -1, dst: 5
op: IXOR_R, src: 3, dst: 0
op: ISUB_R, src: 2, dst: 1
op: IADD_C7, src: -1, dst: 2
op: IXOR_R, src: 0, dst: 1
op: IXOR_R, src: 5, dst: 4
op: IMULH_R, src: 4, dst: 3
op: IMUL_RCP, src: -1, dst: 7
op: IMUL_R, src: 0, dst: 1
op: IMUL_R, src: 0, dst: 2
op: IADD_RS, src: 4, dst: 0
op: ISUB_R, src: 4, dst: 5
op: IXOR_C7, src: -1, dst: 4
op: IXOR_R, src: 6, dst: 0
op: ISUB_R, src: 6, dst: 5
op: IXOR_C7, src: -1, dst: 0
op: ISUB_R, src: 6, dst: 4
op: IXOR_R, src: 7, dst: 4
op: ISMULH_R, src: 7, dst: 6
op: IMUL_RCP, src: -1, dst: 4
op: IMUL_R, src: 5, dst: 3
op: IMUL_R, src: 2, dst: 7
op: IADD_RS, src: 5, dst: 0
op: IADD_RS, src: 2, dst: 0
op: IADD_C8, src: -1, dst: 2
op: IROR_C, src: -1, dst: 3
op: IADD_RS, src: 5, dst: 2
op: IXOR_C8, src: -1, dst: 3
op: IROR_C, src: -1, dst: 2
op: IMUL_R, src: 0, dst: 5
op: IMUL_R, src: 4, dst: 3
op: IMUL_R, src: 4, dst: 2
op: IADD_RS, src: 0, dst: 1
op: ISUB_R, src: 4, dst: 6
op: IXOR_C7, src: -1, dst: 4
op: ISUB_R, src: 0, dst: 6
op: IMULH_R, src: 1, dst: 0
op: IMUL_RCP, src: -1, dst: 1
op: IADD_C9, src: -1, dst: 7
op: ISUB_R, src: 6, dst: 3
op: ISUB_R, src: 6, dst: 2
op: IADD_C7, src: -1, dst: 5
op: IXOR_R, src: 3, dst: 7
op: ISUB_R, src: 3, dst: 6
op: IMUL_R, src: 7, dst: 2
op: IMUL_R, src: 4, dst: 0
op: IMUL_R, src: 6, dst: 5
op: IROR_C, src: -1, dst: 7
op: ISUB_R, src: 1, dst: 7
op: IADD_C7, src: -1, dst: 6
op: ISUB_R, src: 6, dst: 7
op: ISMULH_R, src: 3, dst: 4
op: IMUL_RCP, src: -1, dst: 0
op: IADD_C8, src: -1, dst: 1
op: IADD_RS, src: 6, dst: 2
op: ISUB_R, src: 6, dst: 1
op: IADD_C7, src: -1, dst: 5
op: IXOR_R, src: 3, dst: 2
op: ISUB_R, src: 6, dst: 2
op: IMUL_R, src: 1, dst: 3
op: IMUL_R, src: 7, dst: 6
op: IMUL_R, src: 2, dst: 0
op: IADD_RS, src: 5, dst: 7
op: IADD_RS, src: 2, dst: 7
op: IADD_C9, src: -1, dst: 1
op: ISUB_R, src: 3, dst: 2
op: ISUB_R, src: 3, dst: 1
op: IADD_C7, src: -1, dst: 3
op: ISUB_R, src: 7, dst: 5
op: IMULH_R, src: 0, dst: 4
op: IMUL_RCP, src: -1, dst: 0
op: IMUL_R, src: 7, dst: 1
op: IMUL_R, src: 7, dst: 5
op: IROR_C, src: -1, dst: 3
op: ISUB_R, src: 2, dst: 6
op: IXOR_C7, src: -1, dst: 2
op: IXOR_R, src: 3, dst: 7
op: ISMULH_R, src: 6, dst: 3
op: IMUL_RCP, src: -1, dst: 7
op: IADD_C9, src: -1, dst: 1
op: ISUB_R, src: 0, dst: 2
op: IROR_C, src: -1, dst: 1
op: IADD_C8, src: -1, dst: 5
op: IROR_C, src: -1, dst: 6
op: IMUL_R, src: 1, dst: 4
op: IMUL_R, src: 2, dst: 0
op: IMUL_R, src: 1, dst: 7
op: IADD_RS, src: 5, dst: 2
op: IXOR_R, src: 6, dst: 5
op: IXOR_C7, src: -1, dst: 5
op: IXOR_R, src: 6, dst: 2
op: ISMULH_R, src: 6, dst: 6
op: IMUL_RCP, src: -1, dst: 3
op: IXOR_C8, src: -1, dst: 0
op: IROR_C, src: -1, dst: 5
op: IXOR_R, src: 4, dst: 5
op: IADD_C7, src: -1, dst: 1
op: ISUB_R, src: 4, dst: 0
op: IMULH_R, src: 4, dst: 4
op: IMUL_RCP, src: -1, dst: 6
op: IMUL_R, src: 3, dst: 1
op: IMUL_R, src: 7, dst: 3
op: IADD_RS, src: 5, dst: 0
op: IROR_C, src: -1, dst: 2
op: IXOR_C9, src: -1, dst: 5
op: IXOR_R, src: 7, dst: 2
op: IROR_C, src: -1, dst: 2
op: IXOR_C9, src: -1, dst: 0
op: IXOR_R, src: 4, dst: 2
op: IMUL_R, src: 4, dst: 0
op: IMUL_R, src: 7, dst: 6
op: IMUL_R, src: 3, dst: 5
op: IADD_RS, src: 7, dst: 4
op: IADD_RS, src: 2, dst: 7
op: IADD_C9, src: -1, dst: 2
op: IMULH_R, src: 0, dst: 1
op: IMUL_RCP, src: -1, dst: 3
op: IXOR_C8, src: -1, dst: 2
op: IROR_C, src: -1, dst: 4
op: IADD_RS, src: 2, dst: 6
op: IADD_C9, src: -1, dst: 4
op: IMULH_R, src: 2, dst: 7
op: IMUL_RCP, src: -1, dst: 0
op: IMUL_R, src: 1, dst: 4
op: IMUL_R, src: 1, dst: 6
op: IROR_C, src: -1, dst: 5
op: IADD_RS, src: 2, dst: 1
op: IXOR_C9, src: -1, dst: 3
op: IMULH_R, src: 1, dst: 2
op: IMUL_RCP, src: -1, dst: 3
op: IXOR_C9, src: -1, dst: 5
op: IMULH_R, src: 5, dst: 1
op: IMUL_RCP, src: -1, dst: 5
op: IXOR_C9, src: -1, dst: 0
op: ISMULH_R, src: 2, dst: 7
op: IMUL_RCP, src: -1, dst: 0
op: IADD_C8, src: -1, dst: 6
op: IADD_RS, src: 4, dst: 2
op: IXOR_C7, src: -1, dst: 6
op: IXOR_R, src: 3, dst: 2
op: ISUB_R, src: 4, dst: 3
op: ISUB_R, src: 4, dst: 1
op: IMUL_R, src: 5, dst: 6
op: IMUL_R, src: 5, dst: 1
op: IMUL_R, src: 7, dst: 0
op: IROR_C, src: -1, dst: 2
op: IADD_RS, src: 4, dst: 2
op: IXOR_C9, src: -1, dst: 3
op: IXOR_R, src: 4, dst: 7
op: IROR_C, src: -1, dst: 4
op: IXOR_C8, src: -1, dst: 6
op: IADD_RS, src: 5, dst: 3
op: IMUL_R, src: 7, dst: 6
op: IMUL_R, src: 1, dst: 2
op: IMUL_R, src: 0, dst: 5
op: IADD_RS, src: 7, dst: 4
op: IROR_C, src: -1, dst: 1
op: IXOR_C8, src: -1, dst: 1
op: IADD_RS, src: 3, dst: 4
op: IXOR_C7, src: -1, dst: 7
op: ISUB_R, src: 0, dst: 1
op: IXOR_R, src: 7, dst: 1
op: ISMULH_R, src: 4, dst: 3
op: IMUL_RCP, src: -1, dst: 7
op: IMUL_R, src: 4, dst: 1
op: IMUL_R, src: 0, dst: 4
op: IROR_C, src: -1, dst: 2
op: ISUB_R, src: 5, dst: 0
op: IADD_C7, src: -1, dst: 5
op: IXOR_R, src: 6, dst: 5
op: IXOR_R, src: 0, dst: 4
op: IXOR_R, src: 2, dst: 6
op: IXOR_C7, src: -1, dst: 2
op: IXOR_R, src: 5, dst: 4
op: IXOR_R, src: 7, dst: 0
op: IMUL_R, src: 4, dst: 6
op: IMUL_R, src: 5, dst: 3
op: IMUL_R, src: 5, dst: 2
op: IADD_RS, src: 5, dst: 4
op: ISUB_R, src: 7, dst: 1
op: IXOR_C7, src: -1, dst: 5
op: IXOR_R, src: 4, dst: 0
op: IMULH_R, src: 1, dst: 7
op: IMUL_RCP, src: -1, dst: 0
op: IXOR_C8, src: -1, dst: 1
op: IROR_C, src: -1, dst: 4
op: IROR_C, src: -1, dst: 5
op: IXOR_C9, src: -1, dst: 3
op: ISUB_R, src: 4, dst: 2
op: IMUL_R, src: 4, dst: 5
op: IMUL_R, src: 1, dst: 3
op: IMUL_R, src: 1, dst: 2
op: IADD_RS, src: 1, dst: 6
op: ISUB_R, src: 4, dst: 1
op: IXOR_C7, src: -1, dst: 1
op: ISUB_R, src: 7, dst: 4
op: ISUB_R, src: 5, dst: 4
op: IROR_C, src: -1, dst: 7
op: IADD_C8, src: -1, dst: 1
op: IADD_RS, src: 6, dst: 0
op: IMUL_R, src: 7, dst: 4
op: IMUL_R, src: 5, dst: 1
op: IMUL_R, src: 7, dst: 0
op: IADD_RS, src: 2, dst: 7
op: ISUB_R, src: 6, dst: 3
op: IADD_C7, src: -1, dst: 2
op: IXOR_R, src: 3, dst: 7
op: IXOR_R, src: 4, dst: 3
op: IROR_C, src: -1, dst: 7
op: IXOR_C8, src: -1, dst: 4
op: IADD_RS, src: 4, dst: 6
op: IMUL_R, src: 7, dst: 2
op: IMUL_R, src: 4, dst: 7
op: IMUL_R, src: 0, dst: 4
op: IADD_RS, src: 3, dst: 1
op: IADD_RS, src: 1, dst: 6
op: IADD_C8, src: -1, dst: 3
op: IROR_C, src: -1, dst: 3
op: ISUB_R, src: 1, dst: 0
op: IXOR_C7, src: -1, dst: 1
op: ISUB_R, src: 5, dst: 6
op: IMULH_R, src: 0, dst: 5
op: IMUL_RCP, src: -1, dst: 2
op: IMUL_R, src: 6, dst: 0
op: IMUL_R, src: 4, dst: 3
op: IROR_C, src: -1, dst: 1
op: IXOR_C7, src: -1, dst: 1
op: IXOR_R, src: 7, dst: 4
op: ISUB_R, src: 1, dst: 7
op: IMULH_R, src: 5, dst: 6
op: IMUL_RCP, src: -1, dst: 1
"#;

const EXPECTED_SUPERSCALAR_PROG_RAGE: &str = r#"op: IMUL_R, src: 2, dst: 7
op: IMUL_R, src: 4, dst: 2
op: IMUL_R, src: 4, dst: 1
op: IADD_RS, src: 3, dst: 0
op: IXOR_C7, src: -1, dst: 6
op: IXOR_R, src: 4, dst: 0
op: ISUB_R, src: 6, dst: 3
op: IXOR_R, src: 6, dst: 5
op: IADD_C7, src: -1, dst: 4
op: IXOR_R, src: 7, dst: 5
op: ISUB_R, src: 6, dst: 0
op: IMULH_R, src: 2, dst: 6
op: IMUL_RCP, src: -1, dst: 3
op: IMUL_R, src: 5, dst: 0
op: IMUL_R, src: 2, dst: 5
op: IADD_RS, src: 7, dst: 1
op: IADD_RS, src: 2, dst: 4
op: IADD_C9, src: -1, dst: 7
op: ISUB_R, src: 2, dst: 7
op: IADD_RS, src: 1, dst: 2
op: IXOR_C8, src: -1, dst: 4
op: IROR_C, src: -1, dst: 1
op: IMUL_R, src: 6, dst: 4
op: IMUL_R, src: 7, dst: 6
op: IMUL_R, src: 3, dst: 7
op: IADD_RS, src: 3, dst: 2
op: IXOR_C7, src: -1, dst: 3
op: ISUB_R, src: 1, dst: 2
op: IXOR_R, src: 5, dst: 2
op: ISMULH_R, src: 4, dst: 1
op: IMUL_RCP, src: -1, dst: 6
op: IADD_C8, src: -1, dst: 3
op: IROR_C, src: -1, dst: 3
op: IADD_C7, src: -1, dst: 0
op: IXOR_R, src: 3, dst: 7
op: IXOR_R, src: 5, dst: 0
op: ISUB_R, src: 2, dst: 3
op: IMUL_R, src: 4, dst: 3
op: IMUL_R, src: 0, dst: 7
op: IMUL_R, src: 2, dst: 6
op: IROR_C, src: -1, dst: 5
op: IADD_C7, src: -1, dst: 2
op: IXOR_R, src: 4, dst: 2
op: IXOR_R, src: 4, dst: 0
op: IXOR_R, src: 2, dst: 4
op: IXOR_C7, src: -1, dst: 2
op: IXOR_R, src: 2, dst: 0
op: ISUB_R, src: 2, dst: 1
op: IMULH_R, src: 0, dst: 5
op: IMUL_RCP, src: -1, dst: 6
op: IMUL_R, src: 7, dst: 1
op: IMUL_R, src: 2, dst: 4
op: IROR_C, src: -1, dst: 3
op: IADD_RS, src: 2, dst: 3
op: IADD_C9, src: -1, dst: 0
op: IMULH_R, src: 2, dst: 2
op: IMUL_RCP, src: -1, dst: 3
op: IADD_C9, src: -1, dst: 7
op: IXOR_R, src: 7, dst: 0
op: IADD_C7, src: -1, dst: 6
op: IXOR_R, src: 7, dst: 5
op: ISUB_R, src: 7, dst: 0
op: IXOR_R, src: 7, dst: 1
op: IMUL_R, src: 6, dst: 5
op: IMUL_R, src: 0, dst: 7
op: IMUL_R, src: 4, dst: 1
op: IADD_RS, src: 6, dst: 0
op: ISUB_R, src: 6, dst: 4
op: IADD_C7, src: -1, dst: 0
op: ISUB_R, src: 4, dst: 2
op: ISUB_R, src: 6, dst: 0
op: IADD_RS, src: 5, dst: 6
op: IADD_C9, src: -1, dst: 3
op: ISUB_R, src: 5, dst: 2
op: IMUL_R, src: 7, dst: 3
op: IMUL_R, src: 6, dst: 0
op: IMUL_R, src: 6, dst: 4
op: IROR_C, src: -1, dst: 2
op: IXOR_R, src: 7, dst: 5
op: IADD_C7, src: -1, dst: 5
op: ISUB_R, src: 7, dst: 1
op: IMULH_R, src: 1, dst: 6
op: IMUL_RCP, src: -1, dst: 7
op: IADD_C9, src: -1, dst: 1
op: ISUB_R, src: 2, dst: 3
op: ISUB_R, src: 1, dst: 5
op: IADD_C7, src: -1, dst: 2
op: IXOR_R, src: 2, dst: 5
op: IXOR_R, src: 1, dst: 2
op: IMUL_R, src: 3, dst: 1
op: IMUL_R, src: 2, dst: 3
op: IMUL_R, src: 5, dst: 7
op: IROR_C, src: -1, dst: 2
op: IROR_C, src: -1, dst: 0
op: IXOR_C9, src: -1, dst: 2
op: ISMULH_R, src: 4, dst: 4
op: IMUL_RCP, src: -1, dst: 5
op: IXOR_C8, src: -1, dst: 1
op: IADD_RS, src: 3, dst: 6
op: ISUB_R, src: 1, dst: 2
op: IXOR_C7, src: -1, dst: 2
op: ISUB_R, src: 3, dst: 1
op: ISUB_R, src: 0, dst: 6
op: IMUL_R, src: 2, dst: 6
op: IMUL_R, src: 5, dst: 0
op: IMUL_R, src: 1, dst: 5
op: IADD_RS, src: 1, dst: 7
op: IADD_C7, src: -1, dst: 3
op: ISUB_R, src: 7, dst: 1
op: IXOR_R, src: 3, dst: 7
op: IXOR_R, src: 4, dst: 1
op: IXOR_C7, src: -1, dst: 7
op: IXOR_R, src: 2, dst: 4
op: IXOR_R, src: 3, dst: 6
op: IMULH_R, src: 6, dst: 2
op: IMUL_RCP, src: -1, dst: 5
op: IMUL_R, src: 4, dst: 1
op: IMUL_R, src: 4, dst: 3
op: IADD_RS, src: 6, dst: 0
op: IROR_C, src: -1, dst: 6
op: IADD_C9, src: -1, dst: 7
op: IXOR_R, src: 0, dst: 6
op: IXOR_C7, src: -1, dst: 7
op: ISUB_R, src: 7, dst: 6
op: ISUB_R, src: 4, dst: 7
op: ISMULH_R, src: 4, dst: 4
op: IMUL_RCP, src: -1, dst: 7
op: IMUL_R, src: 0, dst: 2
op: IMUL_R, src: 6, dst: 0
op: IROR_C, src: -1, dst: 5
op: IADD_RS, src: 6, dst: 1
op: IADD_C9, src: -1, dst: 3
op: ISUB_R, src: 5, dst: 1
op: ISUB_R, src: 5, dst: 6
op: IXOR_C7, src: -1, dst: 3
op: ISUB_R, src: 7, dst: 1
op: IXOR_R, src: 3, dst: 5
op: IMUL_R, src: 3, dst: 4
op: IMUL_R, src: 5, dst: 6
op: IMUL_R, src: 0, dst: 3
op: IROR_C, src: -1, dst: 2
op: IROR_C, src: -1, dst: 7
op: IADD_C8, src: -1, dst: 5
op: IADD_RS, src: 7, dst: 0
op: IROR_C, src: -1, dst: 5
op: IADD_C8, src: -1, dst: 7
op: IADD_RS, src: 1, dst: 0
op: IMUL_R, src: 1, dst: 7
op: IMUL_R, src: 5, dst: 1
op: IMUL_R, src: 2, dst: 0
op: IROR_C, src: -1, dst: 4
op: IADD_RS, src: 5, dst: 6
op: IADD_C8, src: -1, dst: 3
op: IROR_C, src: -1, dst: 6
op: IADD_RS, src: 3, dst: 2
op: IADD_C9, src: -1, dst: 5
op: ISUB_R, src: 7, dst: 5
op: IMUL_R, src: 3, dst: 2
op: IMUL_R, src: 4, dst: 3
op: IMUL_R, src: 6, dst: 5
op: IROR_C, src: -1, dst: 7
op: IXOR_C7, src: -1, dst: 7
op: IXOR_R, src: 1, dst: 4
op: IXOR_R, src: 7, dst: 6
op: IXOR_R, src: 0, dst: 4
op: IADD_RS, src: 0, dst: 2
op: IXOR_C8, src: -1, dst: 0
op: IROR_C, src: -1, dst: 6
op: IMUL_R, src: 7, dst: 4
op: IMUL_R, src: 2, dst: 0
op: IMUL_R, src: 3, dst: 6
op: IROR_C, src: -1, dst: 2
op: IADD_RS, src: 5, dst: 7
op: IADD_C9, src: -1, dst: 5
op: IMULH_R, src: 7, dst: 1
op: IMUL_RCP, src: -1, dst: 5
op: IADD_C8, src: -1, dst: 7
op: IADD_RS, src: 0, dst: 2
op: IADD_C7, src: -1, dst: 4
op: IXOR_R, src: 2, dst: 0
op: ISUB_R, src: 6, dst: 7
op: ISUB_R, src: 3, dst: 4
op: IMUL_R, src: 0, dst: 2
op: IMUL_R, src: 4, dst: 7
op: IMUL_R, src: 1, dst: 4
op: IADD_RS, src: 3, dst: 6
op: ISUB_R, src: 0, dst: 1
op: IADD_C7, src: -1, dst: 3
op: IXOR_R, src: 6, dst: 5
op: IMULH_R, src: 0, dst: 0
op: IMUL_RCP, src: -1, dst: 7
op: IADD_C8, src: -1, dst: 1
op: IADD_RS, src: 1, dst: 2
op: IXOR_R, src: 6, dst: 1
op: IADD_C7, src: -1, dst: 4
op: IXOR_R, src: 6, dst: 2
op: IMULH_R, src: 5, dst: 6
op: IMUL_RCP, src: -1, dst: 1
op: IMUL_R, src: 2, dst: 4
op: IMUL_R, src: 5, dst: 7
op: IADD_RS, src: 3, dst: 2
op: IROR_C, src: -1, dst: 3
op: IXOR_C9, src: -1, dst: 0
op: IMULH_R, src: 2, dst: 5
op: IMUL_RCP, src: -1, dst: 4
op: IXOR_C9, src: -1, dst: 3
op: ISUB_R, src: 3, dst: 0
op: IXOR_C7, src: -1, dst: 2
op: ISUB_R, src: 2, dst: 1
op: ISUB_R, src: 2, dst: 3
op: ISUB_R, src: 1, dst: 6
op: IMUL_R, src: 7, dst: 2
op: IMUL_R, src: 6, dst: 0
op: IMUL_R, src: 5, dst: 6
op: IADD_RS, src: 7, dst: 3
op: IADD_RS, src: 1, dst: 3
op: IXOR_C8, src: -1, dst: 1
op: IROR_C, src: -1, dst: 7
op: ISUB_R, src: 4, dst: 5
op: IADD_C7, src: -1, dst: 7
op: IXOR_R, src: 4, dst: 3
op: IMULH_R, src: 4, dst: 1
op: IMUL_RCP, src: -1, dst: 7
op: IMUL_R, src: 4, dst: 5
op: IMUL_R, src: 5, dst: 4
op: IADD_RS, src: 2, dst: 0
op: IADD_C7, src: -1, dst: 3
op: ISUB_R, src: 6, dst: 0
op: IXOR_R, src: 3, dst: 5
op: IXOR_R, src: 2, dst: 6
op: IADD_C7, src: -1, dst: 2
op: ISUB_R, src: 5, dst: 0
op: ISUB_R, src: 3, dst: 6
op: IXOR_R, src: 6, dst: 0
op: IMUL_R, src: 7, dst: 1
op: IMUL_R, src: 0, dst: 6
op: IMUL_R, src: 7, dst: 3
op: IROR_C, src: -1, dst: 5
op: IADD_RS, src: 7, dst: 4
op: IXOR_C8, src: -1, dst: 7
op: IADD_RS, src: 7, dst: 2
op: IADD_RS, src: 4, dst: 1
op: IXOR_C8, src: -1, dst: 0
op: IROR_C, src: -1, dst: 2
op: IMUL_R, src: 0, dst: 4
op: IMUL_R, src: 7, dst: 2
op: IMUL_R, src: 6, dst: 5
op: IROR_C, src: -1, dst: 6
op: IADD_C7, src: -1, dst: 1
op: ISUB_R, src: 7, dst: 6
op: IXOR_R, src: 7, dst: 3
op: ISMULH_R, src: 6, dst: 7
op: IMUL_RCP, src: -1, dst: 6
op: IXOR_C8, src: -1, dst: 2
op: IROR_C, src: -1, dst: 0
op: IADD_C7, src: -1, dst: 4
op: ISUB_R, src: 2, dst: 1
op: ISUB_R, src: 5, dst: 3
op: ISMULH_R, src: 2, dst: 5
op: IMUL_RCP, src: -1, dst: 7
op: IMUL_R, src: 6, dst: 0
op: IMUL_R, src: 3, dst: 2
op: IROR_C, src: -1, dst: 6
op: IADD_RS, src: 4, dst: 1
op: IADD_C9, src: -1, dst: 3
op: IMULH_R, src: 3, dst: 4
op: IMUL_RCP, src: -1, dst: 1
op: IXOR_C8, src: -1, dst: 6
op: IROR_C, src: -1, dst: 3
op: IADD_C7, src: -1, dst: 7
op: IXOR_R, src: 7, dst: 0
op: ISUB_R, src: 5, dst: 7
op: IXOR_R, src: 0, dst: 7
op: IMUL_R, src: 0, dst: 5
op: IMUL_R, src: 3, dst: 0
op: IMUL_R, src: 1, dst: 6
op: IROR_C, src: -1, dst: 2
op: IROR_C, src: -1, dst: 7
op: IADD_C8, src: -1, dst: 2
op: IADD_RS, src: 4, dst: 2
op: IXOR_R, src: 4, dst: 1
op: IXOR_C7, src: -1, dst: 1
op: ISUB_R, src: 7, dst: 4
op: ISMULH_R, src: 3, dst: 3
op: IMUL_RCP, src: -1, dst: 7
op: IMUL_R, src: 1, dst: 2
op: IMUL_R, src: 6, dst: 1
op: IADD_RS, src: 4, dst: 0
op: IXOR_R, src: 0, dst: 4
op: IXOR_C7, src: -1, dst: 0
op: ISUB_R, src: 6, dst: 0
op: ISUB_R, src: 5, dst: 4
op: IROR_C, src: -1, dst: 5
op: IADD_C9, src: -1, dst: 6
op: IXOR_R, src: 7, dst: 5
op: IMUL_R, src: 6, dst: 7
op: IMUL_R, src: 2, dst: 5
op: IMUL_R, src: 0, dst: 6
op: IROR_C, src: -1, dst: 0
op: ISUB_R, src: 0, dst: 2
op: IXOR_C7, src: -1, dst: 4
op: IXOR_R, src: 2, dst: 3
op: IMULH_R, src: 4, dst: 0
op: IMUL_RCP, src: -1, dst: 4
op: IADD_C9, src: -1, dst: 2
op: ISMULH_R, src: 5, dst: 3
op: IMUL_RCP, src: -1, dst: 6
op: IADD_C8, src: -1, dst: 1
op: IROR_C, src: -1, dst: 5
op: IROR_C, src: -1, dst: 1
op: IADD_C8, src: -1, dst: 4
op: IROR_C, src: -1, dst: 7
op: IMUL_R, src: 1, dst: 2
op: IMUL_R, src: 7, dst: 0
op: IMUL_R, src: 5, dst: 1
op: IROR_C, src: -1, dst: 4
op: IADD_C7, src: -1, dst: 7
op: IXOR_R, src: 4, dst: 6
op: ISUB_R, src: 7, dst: 4
op: ISUB_R, src: 4, dst: 6
op: IADD_RS, src: 5, dst: 4
op: IADD_C9, src: -1, dst: 5
op: ISUB_R, src: 0, dst: 4
op: IMUL_R, src: 2, dst: 7
op: IMUL_R, src: 3, dst: 5
op: IMUL_R, src: 4, dst: 6
op: IADD_RS, src: 0, dst: 2
op: IADD_RS, src: 1, dst: 3
op: IXOR_C8, src: -1, dst: 1
op: IADD_RS, src: 2, dst: 1
op: IXOR_C7, src: -1, dst: 0
op: IXOR_R, src: 7, dst: 2
op: ISUB_R, src: 7, dst: 4
op: ISUB_R, src: 7, dst: 0
op: IMUL_R, src: 0, dst: 2
op: IMUL_R, src: 1, dst: 4
op: IMUL_R, src: 6, dst: 3
op: IROR_C, src: -1, dst: 0
op: IXOR_C7, src: -1, dst: 5
op: ISUB_R, src: 6, dst: 0
op: IXOR_R, src: 7, dst: 6
op: ISUB_R, src: 0, dst: 1
op: IADD_RS, src: 5, dst: 7
op: IXOR_C9, src: -1, dst: 6
op: ISUB_R, src: 7, dst: 1
op: IMUL_R, src: 0, dst: 5
op: IMUL_R, src: 7, dst: 6
op: IMUL_R, src: 3, dst: 1
op: IADD_RS, src: 2, dst: 0
op: IROR_C, src: -1, dst: 4
op: IXOR_C9, src: -1, dst: 4
op: ISUB_R, src: 2, dst: 7
op: IROR_C, src: -1, dst: 7
op: IXOR_C8, src: -1, dst: 0
op: IADD_RS, src: 5, dst: 2
op: IMUL_R, src: 5, dst: 0
op: IMUL_R, src: 6, dst: 4
op: IMUL_R, src: 7, dst: 2
op: IROR_C, src: -1, dst: 6
op: IXOR_R, src: 7, dst: 5
op: IXOR_C7, src: -1, dst: 1
op: ISUB_R, src: 5, dst: 7
op: ISUB_R, src: 5, dst: 3
op: IROR_C, src: -1, dst: 7
op: IADD_C8, src: -1, dst: 7
op: IADD_RS, src: 3, dst: 6
op: IMUL_R, src: 1, dst: 3
op: IMUL_R, src: 7, dst: 1
op: IMUL_R, src: 4, dst: 6
op: IADD_RS, src: 0, dst: 4
op: IXOR_C7, src: -1, dst: 5
op: ISUB_R, src: 5, dst: 4
op: IXOR_R, src: 7, dst: 2
op: IMULH_R, src: 4, dst: 0
op: IMUL_RCP, src: -1, dst: 1
op: IXOR_C8, src: -1, dst: 3
op: IADD_RS, src: 7, dst: 2
op: IROR_C, src: -1, dst: 4
op: IADD_C8, src: -1, dst: 3
op: IADD_RS, src: 2, dst: 7
op: IMUL_R, src: 7, dst: 4
op: IMUL_R, src: 7, dst: 3
op: IMUL_R, src: 6, dst: 7
op: IADD_RS, src: 2, dst: 6
op: IROR_C, src: -1, dst: 5
op: IXOR_C8, src: -1, dst: 6
op: IADD_RS, src: 2, dst: 1
op: IADD_C7, src: -1, dst: 2
op: IXOR_R, src: 0, dst: 6
op: IXOR_R, src: 6, dst: 4
op: IMULH_R, src: 4, dst: 0
op: IMUL_RCP, src: -1, dst: 1
op: IMUL_R, src: 2, dst: 6
op: IMUL_R, src: 7, dst: 5
op: IROR_C, src: -1, dst: 3
op: IADD_RS, src: 7, dst: 4
op: IADD_C9, src: -1, dst: 3
op: ISMULH_R, src: 2, dst: 2
op: IMUL_RCP, src: -1, dst: 0
op: IADD_C9, src: -1, dst: 6
op: IMULH_R, src: 1, dst: 7
op: IMUL_RCP, src: -1, dst: 3
op: IXOR_C8, src: -1, dst: 4
op: IROR_C, src: -1, dst: 6
op: IROR_C, src: -1, dst: 5
op: IADD_C9, src: -1, dst: 1
op: ISUB_R, src: 4, dst: 5
op: IMUL_R, src: 1, dst: 4
op: IMUL_R, src: 0, dst: 1
op: IMUL_R, src: 3, dst: 2
op: IADD_RS, src: 6, dst: 0
op: IADD_C7, src: -1, dst: 5
op: IXOR_R, src: 0, dst: 6
op: ISUB_R, src: 5, dst: 0
op: ISMULH_R, src: 4, dst: 5
op: IMUL_RCP, src: -1, dst: 7
op: IADD_C8, src: -1, dst: 4
op: IROR_C, src: -1, dst: 6
op: IXOR_R, src: 0, dst: 4
op: IXOR_C7, src: -1, dst: 2
op: IXOR_R, src: 3, dst: 6
op: ISMULH_R, src: 6, dst: 1
op: IMUL_RCP, src: -1, dst: 4
op: IMUL_R, src: 7, dst: 3
op: IMUL_R, src: 0, dst: 7
op: IADD_RS, src: 0, dst: 2
op: IADD_C7, src: -1, dst: 0
op: ISUB_R, src: 2, dst: 5
op: IXOR_R, src: 6, dst: 5
op: IXOR_R, src: 0, dst: 6
op: ISUB_R, src: 0, dst: 5
op: IADD_C7, src: -1, dst: 2
op: IXOR_R, src: 2, dst: 5
op: IXOR_R, src: 0, dst: 4
op: IMUL_R, src: 2, dst: 0
op: IMUL_R, src: 2, dst: 5
op: IMUL_R, src: 4, dst: 2
op: IADD_RS, src: 4, dst: 1
op: ISUB_R, src: 4, dst: 6
op: IXOR_C7, src: -1, dst: 4
op: ISUB_R, src: 6, dst: 7
op: ISUB_R, src: 7, dst: 3
op: IADD_RS, src: 7, dst: 0
op: IADD_C9, src: -1, dst: 1
op: ISUB_R, src: 4, dst: 7
op: IMUL_R, src: 1, dst: 4
op: IMUL_R, src: 3, dst: 1
op: IMUL_R, src: 7, dst: 3
op: IROR_C, src: -1, dst: 0
op: ISUB_R, src: 0, dst: 2
op: IADD_C7, src: -1, dst: 6
op: ISUB_R, src: 2, dst: 6
op: IXOR_R, src: 2, dst: 0
op: ISUB_R, src: 4, dst: 5
op: IXOR_C7, src: -1, dst: 0
op: IXOR_R, src: 4, dst: 7
op: ISUB_R, src: 1, dst: 2
"#;
